export { default as Main } from './Main'
export { default as Auth } from './Auth'
export { default as Book } from './Book'
export { default as Order } from './Order'
export { default as Basket } from './Basket'
export { default as Mypage } from './Mypage'